language: java

env:
  global:
    secure: WembF1w7EwFQJWwJ7NMRHfPm7UTpsS1iX5gmccJpfy4liTHeDWJCfTpPEtG9qRyTsmpNc8oya8EMUG+Tj9cxobouXxDjVyNo4tgFVGItG2Meqps6roz3hh3GlPE23RDDsoi4C7qD1i8LR0AJP4Bowa8WTHjPOKym/pMqJModbqw=
  
