language: java
script:
- mvn clean install
- git checkout master
- mvn pmd:pmd
- git add .
- mvn pmd:cpd
- git add .
- mvn pmd:check
- git add .
- mvn pmd:cpd-check
- git add .
- mvn checkstyle:checkstyle
- git add .
- mvn clean package
- git add .
- mvn deploy
- git add .
- git config --global user.email ${GIT_EMAIL}
- git config --global user.name ${GIT_NAME}
- git commit -m "lib-calculadora - commit da build travis"
- git push -fq https://hivanamcd:${GH_TOKEN}@github.com/hivanamcd/lib-calculadora.git
  master
after_success:
- BUILD_NBR=$((TRAVIS_JOB_ID - 1))
- echo "Build Number > '${BUILD_NBR}'"
- git config --global user.email ${GIT_EMAIL}
- git config --global user.name ${GIT_NAME}
- git tag -a ${BUILD_NBR} -m "Tag travis"
- git push https://hivanamcd:${GH_TOKEN}@github.com/hivanamcd/lib-calculadora.git
  --tags
env:
  global:
    secure: YKc6a9Gr9Qvpm2khy8ZmqwQnY8R380imPCJFJYqPJwiHL74F3WgTbe76VPLuhiZKr+rvlmfQx98f79wTZ/hWwfiI2eb2Gb+CX73wcR4G+1dvF68q6HagBs0vYxIYn6phRgUvXvi/gQqoROEs//m9/BYid/iaq9gnw5aQwo6aO/4=
